#!/bin/sh
echo
echo
good_flag_path="drawonboard.png"
if [ ! -f "$good_flag_path" ]; then
  echo "This script must be run from the directory containing $good_flag_path"
  exit 1
fi

# system values
icons_root=/usr/local/share/pixmaps
applications_root=/usr/local/share/applications
# project values
project_unix_name=drawonboard
icon_name=drawonboard.png
install_method_tip="sudo ./install"
# derived values
# subicons_dest_dir=$icons_root/$project_unix_name
icon_dest_path=$icons_root/$icon_name

if [ ! -d "/usr/local/lib/$project_unix_name" ]; then
  sudo mkdir -p "/usr/local/lib/$project_unix_name"
fi
sudo cp run.py /usr/local/lib/$project_unix_name/

if [ ! -d "$applications_root" ]; then
  sudo mkdir -p $applications_root
fi
if [ ! -d "$applications_root" ]; then
  echo "ERROR: this script must be run as root or with '$install_method_tip' (could not create $applications_root)"
  exit 12
fi


if [ ! -f "$project_unix_name.desktop" ]; then
  echo "missing $project_unix_name.desktop"
  exit 1
fi
sudo cp $project_unix_name.desktop $applications_root/

if [ ! -f "$applications_root/$project_unix_name.desktop" ]; then
  echo "ERROR: this script must be run as root or with '$install_method_tip' (could not create $applications_root/$project_unix_name.desktop)"
  exit 13
fi
if [ ! -d "$icons_root" ]; then
  sudo mkdir -p "$icons_root"
fi
if [ -f "$icon_dest_path" ]; then
  echo "Removing old $icon_dest_path..."
  rm "$icon_dest_path"
fi

if [ -f "$icon_dest_path" ]; then
  echo "ERROR: this script must be run as root or with '$install_method_tip' (could not remove old $icon_dest_path)"
  exit 9
fi

sudo cp "$icon_name" "$icon_dest_path"

if [ ! -f "$icon_dest_path" ]; then
  echo "ERROR: this script must be run as root or with '$install_method_tip' (could not copy icon $icon_name to new file $icon_dest_path)"
  exit 10
fi

